# Generated by Django 4.2.21 on 2025-05-31 12:41

from django.db import migrations
import phonenumbers

def populate_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
                if phonenumbers.is_valid_number(parsed_number):
                    flat.owner_pure_phone = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                    flat.save()
            except phonenumbers.NumberParseException:
                continue

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_owner_pure_phone_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.RunPython(populate_owner_pure_phone),
    ]
