# Generated by Django 4.2.21 on 2025-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '009_auto_20250610_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_deprecated',
            field=models.ManyToManyField(related_name='flats', to='property.Owner', verbose_name='Собственники квартиры'),
        ),
    ]
