# Generated by Django 4.2.21 on 2025-06-10 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_flat_owner_deprecated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_deprecated',
        ),
    ]
