# Generated by Django 4.2.21 on 2025-06-10 12:26

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owners = Owner.objects.filter(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )

        if owners.exists():
            flat.owners.set(owners)

        else:
            owner, created = Owner.objects.get_or_create(
                full_name=flat.owner,
                phone_number=flat.owners_phonenumber,
                owner_pure_phone=flat.owner_pure_phone
            )
            flat.owners.add(owner)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_flat_owner_deprecated'),
    ]

    operations = [
        migrations.RunPython(link_flats_to_owners),
    ]
